services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_gateway
    environment:
      POSTGRES_DB: payment_gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
    ports:
      - "5432:5432"
    # UPDATED: Direct paths to your SQL files
    volumes:
      - ./backend/db/migrations/create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./backend/db/seeds/seed_merchant.sql:/docker-entrypoint-initdb.d/02_seed_merchant.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway_user -d payment_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gateway_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: gateway_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://gateway_user:gateway_pass@postgres:5432/payment_gateway
      REDIS_URL: redis://redis:6379 
      PORT: 8000
      TEST_MERCHANT_EMAIL: test@example.com
      TEST_API_KEY: key_test_abc123
      TEST_API_SECRET: secret_test_xyz789
      UPI_SUCCESS_RATE: 0.90
      CARD_SUCCESS_RATE: 0.95
      PROCESSING_DELAY_MIN: 5000
      PROCESSING_DELAY_MAX: 10000
      TEST_MODE: "false"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_dashboard
    ports:
      - "3000:80"
    depends_on:
      - api

  checkout:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_checkout
    ports:
      - "3001:80"
    depends_on:
      - api